/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.ServerSql;
import DAO.TipoServidor;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import modelo.clases.ClaseBD;
import modelo.clases.ClaseModelo;

/**
 *
 * @author adminj
 */
public class Principal extends javax.swing.JFrame {

    DAO.DAO dao;
    ServerSql svr;

    /**
     * Creates new form Principal
     *
     * @throws java.lang.ClassNotFoundException
     */
    public Principal() throws ClassNotFoundException {
        initComponents();
        svr= new ServerSql();

        switch (System.getProperty("os.name").toLowerCase()) {

            case "linux":
                this.CBSOperativo.setSelectedIndex(1);
                break;
            default:
                this.CBSOperativo.setSelectedIndex(0);
                break;
        }
          
        this.CBTipoServidor.setModel(new DefaultComboBoxModel(TipoServidor.values()));
        cargarCadenaConexion();
       // this.cargarDriver();
    }

    private void cargarCadenaConexion() {
        svr.setBasedatos(this.CBOBD.getSelectedItem().toString());

        svr.setPassword(this.TxtPassword.getText());
        svr.setUsuario(this.TxtUser.getText());
        svr.setIp("localhost");
//        Parametros.conf conf = new Parametros.conf();
        switch (TipoServidor.valueOf(this.CBTipoServidor.getSelectedItem().toString())) {
            case derby:                
                svr.setPuerto("1527");
                break;
            case mysql:
            case mariadb:    
              svr.setPuerto("3306");
                break;
            case oracle:
                svr.setPuerto("1521");
                break;

        }
        svr.getDriverClass( TipoServidor.valueOf(this.CBTipoServidor.getSelectedItem().toString()));

        this.TxtCadenaConexion.setText(svr.getCadenaConexion());
        //Parametros.conf.strconex= this.TxtCadenaConexion.getText();

    }

//        
    //dao= new DAO.DAO(this.TxtCadenaConexion.getText(),this.TxtUser.getText(),this.TxtPassword.getText());
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CB_BDTablas = new javax.swing.JComboBox();
        CB_Columnas = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Btn_ConectarBD = new javax.swing.JButton();
        Btn_VerTablas = new javax.swing.JButton();
        Btn_CrearClases = new javax.swing.JButton();
        BtnCargar = new javax.swing.JButton();
        CB_BDatos = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        TxtUser = new javax.swing.JTextField();
        TxtDireccionIp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtPassword = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TxtDirectorio = new javax.swing.JTextField();
        CBSOperativo = new javax.swing.JComboBox();
        CBOBD = new javax.swing.JComboBox();
        CBTipoServidor = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        JTPanelGeneral = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        TxtAreaN2 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtAreaN1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtAreaN3 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        TxtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CBOLicencia = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        TxtAutor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TxtPuerto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TxtCadenaConexion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        CB_BDTablas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_BDTablasItemStateChanged(evt);
            }
        });
        CB_BDTablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_BDTablasActionPerformed(evt);
            }
        });

        jLabel1.setText("Tablas :");

        jLabel2.setText("Campos :");

        Btn_ConectarBD.setText("Conectar");
        Btn_ConectarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ConectarBDActionPerformed(evt);
            }
        });

        Btn_VerTablas.setText("Ver tabla");
        Btn_VerTablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_VerTablasActionPerformed(evt);
            }
        });

        Btn_CrearClases.setText("GuardarTodo");
        Btn_CrearClases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CrearClasesActionPerformed(evt);
            }
        });

        BtnCargar.setText("Generar");
        BtnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCargarActionPerformed(evt);
            }
        });

        CB_BDatos.setEditable(true);
        CB_BDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_BDatosActionPerformed(evt);
            }
        });

        jLabel5.setText("Base de Datos :");

        TxtUser.setText("postal");
        TxtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUserActionPerformed(evt);
            }
        });

        TxtDireccionIp.setText("localhost");
        TxtDireccionIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDireccionIpActionPerformed(evt);
            }
        });

        jLabel6.setText("IP:");

        jLabel7.setText("Usuario:");

        jLabel8.setText("Password:");

        TxtPassword.setText("postal");
        TxtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPasswordActionPerformed(evt);
            }
        });

        jLabel9.setText("Dir Proyecto:");

        TxtDirectorio.setText("/home/zeus/java/");
        TxtDirectorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDirectorioActionPerformed(evt);
            }
        });

        CBSOperativo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "WINDOWS", "LINUX" }));
        CBSOperativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBSOperativoActionPerformed(evt);
            }
        });

        CBOBD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Academia", "sample", "PROCEDIMIENTOS", " " }));
        CBOBD.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBOBDItemStateChanged(evt);
            }
        });
        CBOBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBOBDActionPerformed(evt);
            }
        });

        CBTipoServidor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DerbyBD", "MySql", "SQLServer", "MariaDB", " " }));
        CBTipoServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBTipoServidorActionPerformed(evt);
            }
        });

        jLabel10.setText("Servidor SQL:");

        JTPanelGeneral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JTPanelGeneral.setOpaque(true);

        TxtAreaN2.setColumns(20);
        TxtAreaN2.setRows(5);
        jScrollPane3.setViewportView(TxtAreaN2);

        JTPanelGeneral.addTab("ClaseDAO", jScrollPane3);

        TxtAreaN1.setColumns(20);
        TxtAreaN1.setRows(5);
        jScrollPane2.setViewportView(TxtAreaN1);

        JTPanelGeneral.addTab("DAO", jScrollPane2);

        TxtAreaN3.setColumns(20);
        TxtAreaN3.setRows(5);
        jScrollPane1.setViewportView(TxtAreaN3);

        JTPanelGeneral.addTab("Clase", jScrollPane1);

        jLabel3.setText("Email:");

        TxtEmail.setText("micorreo@gmail.com");

        jLabel4.setText("Licencia:");

        CBOLicencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GPL", "BSD", "APACHE", "PROPIETARIA" }));

        jLabel11.setText("Autor:");

        TxtAutor.setText("Escribe tu nombre");

        jLabel12.setText("Puerto:");

        TxtPuerto.setText("1527");

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("GENERADOR DE CLASES PARA JAVA");

        TxtCadenaConexion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtCadenaConexion.setText("Cadena de conexion");
        TxtCadenaConexion.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(CBTipoServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(CB_BDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Btn_ConectarBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtDireccionIp, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CBOBD, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(1, 1, 1)
                        .addComponent(CB_BDTablas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(CB_Columnas, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_VerTablas, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtEmail))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(CBSOperativo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(TxtDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Btn_CrearClases, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel11)
                                .addGap(9, 9, 9)
                                .addComponent(TxtAutor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CBOLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addComponent(JTPanelGeneral)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(TxtCadenaConexion)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(2, 2, 2)
                .addComponent(TxtCadenaConexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CBTipoServidor)
                    .addComponent(jLabel6)
                    .addComponent(TxtDireccionIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBOBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(TxtPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TxtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(TxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(CB_BDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_ConectarBD))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CB_BDTablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(CB_Columnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCargar)
                    .addComponent(Btn_VerTablas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(CBSOperativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_CrearClases))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(CBOLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(TxtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JTPanelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_ConectarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ConectarBDActionPerformed
        // TODO add your handling code here:
        this.cargarCadenaConexion();
        try {
            this.CB_BDTablas.removeAllItems();
            dao = new DAO.DAO();
            dao.svr=svr;

            for (Object a : dao.getTablesFromDB().toArray()) {
                this.CB_BDTablas.addItem(a.toString());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Btn_ConectarBDActionPerformed

    private void Btn_VerTablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_VerTablasActionPerformed
        try {
            // TODO add your handling code here:
            int num = this.CB_BDTablas.getSelectedIndex();
            if (num > -1) {
                String a = this.CB_BDTablas.getModel().getElementAt(num).toString();
                GUI.Dialog f = new GUI.Dialog(this, true, dao.getSelectInto("SELECT * FROM " + a));
                f.setVisible(true);
            }

        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Btn_VerTablasActionPerformed

    private void CB_BDTablasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_BDTablasItemStateChanged
        this.CB_Columnas.removeAll();
        this.CB_Columnas.removeAllItems();
        if (this.CB_BDTablas.getSelectedItem() != null) {
            try {
                this.CB_Columnas.removeAll();
                String ta = this.CB_BDTablas.getSelectedItem().toString();
                for (Object a : dao.getColumnasFromTable(ta).toArray()) {
                    this.CB_Columnas.addItem(a.toString());
                }
            } catch (SQLException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_CB_BDTablasItemStateChanged

    private void CB_BDTablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_BDTablasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_BDTablasActionPerformed

    private void BtnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCargarActionPerformed
        // TODO add your handling code here:
        this.cargarCadenaConexion();
        ClaseModelo clase = null;
//        try {
        // public DAO(String str_class, String str_driver, String user, String passw) 
        //public DAO(String str_driver, String user, String passw)
        //dao = new DAO.DAO( ""  ,this.TxtUser.getText(),this.TxtPassword.getText() );

        System.out.println(this.CB_BDTablas.getSelectedItem().toString());

        try {
            clase = new ClaseModelo(dao.getTabla(this.CB_BDTablas.getSelectedItem().toString()));
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

//        } catch (ClassNotFoundException | SQLException ex) {
//            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
//        }
        String texto = "";
        texto += clase.getLicencia();
        texto += clase.getEncabezado();
        texto += clase.getAutor(this.TxtAutor.getText(), this.TxtEmail.getText());
        texto += clase.getImports();
        texto += clase.getInicioClase();
        texto += clase.getVariables();
        texto += clase.getConstructor();
        texto += clase.getPropiedades();
        texto += clase.getFinClase();
        this.TxtAreaN3.setText(texto);

        modelo.clases.ClaseModeloDao c = new modelo.clases.ClaseModeloDao(clase.getTabla());
        String tx = "";
        tx += c.getLicencia();
        tx += c.getEncabezado();
        tx += c.getAutor(this.TxtAutor.getText(), this.TxtEmail.getText());
        tx += c.getImports();
        tx += c.getInicioClase();
        tx += c.metodoSelect();
        tx += c.metodoDelete();
        tx += c.getFinClase();

        this.TxtAreaN2.setText(tx);

        String txb = "";
        txb += ClaseBD.getLicencia();
        txb += ClaseBD.getEncabezado();
        txb += ClaseBD.getAutor(this.TxtAutor.getText(), this.TxtEmail.getText());
        txb += ClaseBD.importPackages();
        txb += ClaseBD.getConectarClase(this.TxtDireccionIp.getText(), this.TxtUser.getText(), this.TxtPassword.getText());
        txb += ClaseBD.metodoSelect();
        txb += ClaseBD.metodoUpdate();
        txb += ClaseBD.metodoInsertInto();
        txb += ClaseBD.metodoDelete();
        txb += ClaseBD.metodoCount();
        txb += ClaseBD.getFinClase();
        this.TxtAreaN1.setText(txb);

    }//GEN-LAST:event_BtnCargarActionPerformed

    private void Btn_CrearClasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CrearClasesActionPerformed
        // TODO add your handling code here:
////        // creamos archivos de proyecto
         this.cargarCadenaConexion();
        String pro = this.TxtDireccionIp.getText();
        pro = pro.substring(pro.lastIndexOf("/") + 1, pro.length());
        System.out.println(pro);
        try {
            modelo.FFile.saveFile(this.TxtDirectorio.getText(), "build.xml", modelo.Cbuild.getBuildxml(pro));
            modelo.FFile.saveFile(this.TxtDirectorio.getText(), "manifest.mf", modelo.Cbuild.getManifest());
            // crear dir nbproject
            modelo.FFile.crearDir(this.TxtDirectorio.getText() + "nbproject/");
            // creamos fichero project.properties en directorio nbproject
            modelo.FFile.saveFile(this.TxtDirectorio.getText() + "nbproject/", "project.properties", modelo.Cbuild.getProject_properties(pro));

        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
////        // Crear ficheros DAO 
        String ntabla = this.CB_BDTablas.getItemAt(this.CB_BDTablas.getSelectedIndex()).toString(),
                ruta = this.TxtDirectorio.getText() + "DAO/";
//      
        String txb = "";
        txb += ClaseBD.getLicencia();
        txb += ClaseBD.getEncabezado();
        txb += ClaseBD.getAutor(this.TxtAutor.getText(), this.TxtEmail.getText());
        txb += ClaseBD.importPackages();
        txb += ClaseBD.getConectarClase(this.TxtDireccionIp.getText(), this.TxtUser.getText(), this.TxtPassword.getText());
        txb += ClaseBD.metodoSelect();
        txb += ClaseBD.metodoUpdate();
        txb += ClaseBD.metodoInsertInto();
        txb += ClaseBD.metodoDelete();
        txb += ClaseBD.metodoCount();
        txb += ClaseBD.getFinClase();

        try {
            System.out.println(ruta);
            modelo.FFile.saveFile(ruta, "DAO.java", txb);
            System.out.println(ruta + "----");
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
////        //************ crear fichero de clase modelo *******//

        for (int j = 0; j < this.CB_BDTablas.getModel().getSize(); j++) {
            ntabla = this.CB_BDTablas.getModel().getElementAt(j).toString();
            ruta = this.TxtDirectorio.getText() + "modelo/";
            System.out.println(ruta);

            ntabla = ntabla.toLowerCase();
            ClaseModelo clase = null;
            try {
                dao = new DAO.DAO();

                System.out.println(this.CB_BDTablas.getSelectedItem().toString());

                clase = new ClaseModelo(dao.getTabla(this.CB_BDTablas.getSelectedItem().toString()));

            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }

            String texto = "";
            texto += clase.getLicencia();
            texto += clase.getEncabezado();
            texto += clase.getAutor(this.TxtAutor.getText(), this.TxtEmail.getText());
            texto += clase.getImports();
            texto += clase.getInicioClase();
            texto += clase.getVariables();
            texto += clase.getConstructor();
            texto += clase.getPropiedades();
            texto += clase.getFinClase();

            try {
                modelo.FFile.saveFile(ruta, ntabla.toLowerCase() + ".java", texto);

            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
            clase = null;
        }

    }//GEN-LAST:event_Btn_CrearClasesActionPerformed

    private void CBSOperativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBSOperativoActionPerformed
        // TODO add your handling code here:
        switch (this.CBSOperativo.getItemAt(this.CBSOperativo.getSelectedIndex()).toString().toUpperCase()) {
            case "WINDOWS":
                this.TxtDirectorio.setText("e:/java/");
                break;
            case "LINUX":
                this.TxtDirectorio.setText("/home/zeus/java/");
                break;

        }

    }//GEN-LAST:event_CBSOperativoActionPerformed

    private void TxtDireccionIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDireccionIpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDireccionIpActionPerformed

    private void CBOBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBOBDActionPerformed
        // TODO add your handling code here:
       
       // this.TxtDireccionIp.setText( this.CBOBD.getSelectedItem().toString());
        switch (this.CBOBD.getSelectedItem().toString()) {
            case "Academia":
                this.TxtUser.setText("postal");
                this.TxtPassword.setText("postal");
                break;
            case "sample":
                this.TxtUser.setText("app");
                this.TxtPassword.setText("app");
                break;
            case "PROCEDIMIENTOS":
                this.TxtUser.setText("juez");
                this.TxtPassword.setText("zeuj");
                break;
            default:
                this.TxtUser.setText("postal");
                this.TxtPassword.setText("postal");
                break;
        }
        this.cargarCadenaConexion();

    }//GEN-LAST:event_CBOBDActionPerformed

    private void CBOBDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBOBDItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_CBOBDItemStateChanged

    private void TxtDirectorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDirectorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDirectorioActionPerformed

    private void CBTipoServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBTipoServidorActionPerformed
        // TODO add your handling code here:
        this.cargarCadenaConexion();
        
    }//GEN-LAST:event_CBTipoServidorActionPerformed

    private void TxtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUserActionPerformed
        // TODO add your handling code here:
        this.cargarCadenaConexion();
    }//GEN-LAST:event_TxtUserActionPerformed

    private void TxtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPasswordActionPerformed
        // TODO add your handling code here:
        this.cargarCadenaConexion();
    }//GEN-LAST:event_TxtPasswordActionPerformed

    private void CB_BDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_BDatosActionPerformed
        // TODO add your handling code here:
        this.cargarCadenaConexion();
    }//GEN-LAST:event_CB_BDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new Principal().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCargar;
    private javax.swing.JButton Btn_ConectarBD;
    private javax.swing.JButton Btn_CrearClases;
    private javax.swing.JButton Btn_VerTablas;
    private javax.swing.JComboBox CBOBD;
    private javax.swing.JComboBox CBOLicencia;
    private javax.swing.JComboBox CBSOperativo;
    private javax.swing.JComboBox CBTipoServidor;
    private javax.swing.JComboBox CB_BDTablas;
    private javax.swing.JComboBox CB_BDatos;
    private javax.swing.JComboBox CB_Columnas;
    private javax.swing.JTabbedPane JTPanelGeneral;
    private javax.swing.JTextArea TxtAreaN1;
    private javax.swing.JTextArea TxtAreaN2;
    private javax.swing.JTextArea TxtAreaN3;
    private javax.swing.JTextField TxtAutor;
    private javax.swing.JTextField TxtCadenaConexion;
    private javax.swing.JTextField TxtDireccionIp;
    private javax.swing.JTextField TxtDirectorio;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtPassword;
    private javax.swing.JTextField TxtPuerto;
    private javax.swing.JTextField TxtUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
